### DISCUSSION TITLE
Test deployment

### DISCUSSION THREAD

**Discussion by jimtyrro** [siderolabs/talos-cloud-controller-manager#16] [General]
I'm trying to deploy this controller but I'm getting the following error in regards to the secret.

`serviceaccount/talos-cloud-controller-manager created`
`configmap/talos-cloud-controller-manager created`
`clusterrole.rbac.authorization.k8s.io/system:talos-cloud-controller-manager created`
`clusterrolebinding.rbac.authorization.k8s.io/system:talos-cloud-controller-manager created`
`rolebinding.rbac.authorization.k8s.io/system:talos-cloud-controller-manager:extension-apiserver-authentication-reader created`
`deployment.apps/talos-cloud-controller-manager created`
`error: resource mapping not found for name: "talos-cloud-controller-manager-talos-secrets" namespace: "kube-system" from "https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml": no matches for kind "ServiceAccount" in version "talos.dev/v1alpha1"
ensure CRDs are installed first`

**Comment by sergelogvinov** [comment]
Hello, I think you forgot to allow talos CRDs features: https://github.com/siderolabs/talos-cloud-controller-manager#prepare-control-plane or https://www.talos.dev/v1.2/reference/configuration/#kubernetestalosapiaccessconfig

Add this to your control-plane machine config:
```yaml
machine:
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system
```
