### DISCUSSION TITLE
Passing in transformation configuration when deploying TalosCCM via machineConfig?

### DISCUSSION THREAD

**Discussion by nogweii** [siderolabs/talos-cloud-controller-manager#165] [Q&A]
Is there a way to pass additional configuration values to TalosCCM when I'm deploying it [via the machineConfig](https://github.com/siderolabs/talos-cloud-controller-manager?tab=readme-ov-file#method-1-talos-machine-config)?

I'd like to add node transformation rules, to add labels. But since the manifest has a ConfigMap, I think this might not be so easy?

**Comment by sergelogvinov** [comment]
I did not test it, but...

```yaml
cluster:
  inlineManifests:
    - name: talos-cloud-controller-manager
      contents: |-
        apiVersion: v1
        kind: ConfigMap
        type: Opaque
        metadata:
          name: talos-cloud-controller-manager
          namespace: kube-system
        data:
          ccm-config.yaml: |
            global:
            transformations:
```
