### ISSUE TITLE
"node-csr-approval" is not in the list of known controllers

### ISSUE THREAD

**Issue by nogweii** [siderolabs/talos-cloud-controller-manager#193]
### Description
With the most recent chart release, talos-ccm crash loops with the error message that it doesn't recognize the controller name. I figure it's because there wasn't a version released that included the code yet, although the chart is configured for it.

### Logs

```
"node-csr-approval" is not in the list of known controllers
E0828 19:00:49.247979       1 run.go:74] "command failed" err="\"node-csr-approval\" is not in the list of known controllers"
```

(I had to manually approve the node's CSR to get the logs, avoiding a catch-22 I found myself in before realizing that was an option. I thought I can't capture the logs as there is a TLS error, but the error won't be resolved as talos-ccm isn't running. :smile: )

### Environment

- Talos CCM version: 1.6
- Talos version: 1.7.6
- Kubernetes version: 1.30.1
- Platform: metal

**Comment by sergelogvinov** [comment]
Hi, this param appears here https://github.com/siderolabs/talos-cloud-controller-manager/blob/main/docs/deploy/cloud-controller-manager-edge.yml for `edge` version. It has `imagePullPolicy: Always` policy.

How do you deploy the CCM ?

**Comment by nogweii** [comment]
I'm using [Helmfile](https://github.com/helmfile/helmfile) to deploy, with the following configuration entry:

```yaml
releases:
  - name: talos-cloud-controller-manager
    namespace: kube-system
    chart: oci://ghcr.io/siderolabs/charts/talos-cloud-controller-manager
    version: 0.4.0
    values:
      - ./chart-values/talos-ccm.yaml
```

**Comment by sergelogvinov** [comment]
Thank you for feedback. Yap not I see what append here.

I update the documentation and remove `node-csr-approval` controller by default #194

**Comment by sergelogvinov** [comment]
merged

**Comment by Rhymen** [comment]
I deployed the helm chart 0.4.1 with the example values.yaml from the [README.md](https://github.com/siderolabs/talos-cloud-controller-manager/blob/main/charts/talos-cloud-controller-manager/README.md)

```
# talos-ccm.yaml

replicaCount: 2

enabledControllers:
  - cloud-node
  - node-csr-approval

# Deploy CCM only on control-plane nodes
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
```

I get the same error as explained in the issue here:
"node-csr-approval" is not in the list of known controllers

Environment
- Talos CCM Helm Chart: 0.4.1
- Talos CCM version: 1.6.0
- Talos version: 1.7.6
- Kubernetes version: 1.30.3
- Platform: metal
