### ISSUE TITLE
transformations rules: access status.nodeInfo variables inside templates

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos-cloud-controller-manager#232]
### Description

Make possible to access node info variables, like systemUUID, machineID in transformations template rules

```yaml
  nodeInfo:
    architecture: amd64
    bootID: f7fca4d8-49ba-4e30-86b7-34a46ab51955
    containerRuntimeVersion: containerd://1.7.13
    kernelVersion: 6.1.82-talos
    kubeProxyVersion: v1.30.8
    kubeletVersion: v1.30.8
    machineID: 1afa82f9c1b271f8672c6737d8185535
    operatingSystem: linux
    osImage: Talos (v1.6.7)
    systemUUID: 3ff4ba2c-1927-49b7-a21e-ff89cb0d874e
```

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
