### ISSUE TITLE
Is there any way to use transformation rules on Metal platform

### ISSUE THREAD

**Issue by rouke-broersma** [siderolabs/talos-cloud-controller-manager#250]
## Feature Request

Support transformations rules on metal platform for at least hostname

### Description

I am using the Metal platform, and would like to use transformation rules to automatically set node labels and taints, however it seems like the Metal platform does not store the required information in the api that talos ccm is using. Talos knows the node hostnames from the talos config that is applied to the nodes, but this does not seem to set PlatformMetadatas:

```
get PlatformMetadatas -o yaml
node: 10.0.102.55
metadata:
    namespace: runtime
    type: PlatformMetadatas.talos.dev
    id: platformmetadata
    version: 2
    owner: network.PlatformConfigController
    phase: running
    created: 2025-03-24T21:18:48Z
    updated: 2025-03-24T21:18:57Z
spec:
    platform: metal
    instanceId: 9b6acca8-22d3-4b86-8ce0-9ca0cff32a2b
```

It would be great if talos ccm could fallback to the node name as the hostname, because I can then use `platformMetadata` transform to fill other platform metadata fields, on which I can build other transformation rules.

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
