### ISSUE TITLE
Change metadata variables

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos-cloud-controller-manager#3]
Can possible to change variables received from the metadata server.

Openstack does not have region in metadata source.
We can add to nodename the region:

```yaml
- match:
    platform: openstack
  matchRe:
    nodename: worker-(\w+)-([0-9]+)
  result:
    region: {{ index .matcher.nodename 0 }}
    providerID: openstack://{{ index .matcher.nodename 0 }}/{{ .instanceID }}
```

**Comment by TimJones** [comment]
I think a much simpler solution is to simply not add the kubernetes region label (or any label) to a node if the metadata doesn't have an equivalent.

**Comment by sergelogvinov** [comment]
Source metadata values and transformation rules

command: `talosctl get PlatformMetadatas.talos.dev -oyaml`

### Oracle instance 
```yaml
platform: oracle
hostname: web-oci-ad2-1
region: eu-frankfurt-1
zone: EU-FRANKFURT-1-AD-2
instanceType: VM.Standard.A1.Flex
instanceId: ocid1.instance.oc1.eu-frankfurt-1.aaaaaaaabbbbbbccccccdddddd
providerId: oci://ocid1.instance.oc1.eu-frankfurt-1.aaaaaaaabbbbbbccccccdddddd
```

### Openstack 

```yaml
platform: openstack
hostname: web-fra-de11
zone: nova
instanceType: b2-7
instanceId: 9a1fd9ee-9f05-473e-88d8-1b1b1b1b1b1b
providerId: openstack:///9a1fd9ee-9f05-473e-88d8-1b1b1b1b1b1b
```

### Talos CCM config rules


```yaml
  rules:
    - name: oracle
      # Match rules similar as kubernetes matchExpressions
      match:
        - name: oracle vm in frankfurt
          matchExpressions:
            # and operator
            - key: platform
              operator: In
              values:
                - oracle
            - key: region
              operator: In
              values:
                - eu-frankfurt-1
        # or
        - name: special vm name
          matchExpressions:
            - key: hostname
              operator: Regexp
              values:
                - ^web-oci-ad2-.+$

      # We will annotate and label the nodes
      annotations:
        oci.oraclecloud.com/instance-id: "{{ .instanceId }}" <-- go template
        oci.oraclecloud.com/compartment-id: ocid1.compartment.oc1..aaaaaaaabbbbbbccccccdddddd
      labels:
        talos.dev/zone": "frankfurt"
        node-role.kubernetes.io/web: ""

      # Transforme the platformMetadata
      platformMetadata:
        zone: EU-FRANKFURT-1-AD-2

    - name: openstack
      match:
        - name: fix openstack zone
          matchExpressions:
            - key: platform
              operator: In
              values:
                - openstack
            - key: zone
              operator: In
              values:
                - nova
            - key: hostname
              operator: Regexp
              values:
                - ^web-fra-.+$
      annotations: {}
      labels:
        talos.dev/zone: "frankfurt"
        node-role.kubernetes.io/web: ""

      # Set providerId/region/zone based on the hostname and platform
      platformMetadata:
        zone: frankfurt
        region: eu-frankfurt-1
        providerId: "openstack://fra/{{ .instanceId }}"

      # Special features for the node
      features:
        publicIPPredict: true
```
